dataset_path: data
seed: 42
num_epoch: 100
data_loader:
  common:
    num_voxel_bins: 15
  train:
    batch_size: 16
    shuffle: false
  test:
    batch_size: 1
    shuffle: false
train:
  no_batch_norm: false
  initial_learning_rate: 0.003
  learning_rate_decay: 0.9
  weight_decay: 0.0001
  smoothness_weight: 0.5
  epochs: 100
